name-template: "v$NEXT_MINOR_VERSION"
tag-template: "v$NEXT_MINOR_VERSION"
categories:
  - title: "âœ¨ Features"
    label: "enhancement"
  - title: "ğŸ› Fixes"
    label: "bug"
  - title: "ğŸ“ Documentation"
    label: "documentation"
change-template: "- $TITLE #$NUMBER @$AUTHOR"
template: |
  $CHANGES
